name: NER Train Module
family_id: ceba38fe-47d0-44b6-8909-981f5e92bae3
category: Machine Learning\Train
description: NER train module
inputs:
- name: Input train data
  type: Dataset
  connectable: True
  default: ""
  description: input train data
- name: BERT pretrained model
  type: Mode
  connectable: False
  default: "bert-base-cased"
  description: Specify BERT pretrained model
  options:
    - bert-base-uncased
    - bert-base-cased
    - bert-large-uncased
    - bert-large-cased
- name: Maximum sequence length
  type: Int
  connectable: False
  default: 128
  description: Specify maximum sequence length
- name: Number of training epochs
  type: Int
  connectable: False
  default: 5
  description: Specify number of training epochs
    training
- name: Warmup proportion
  type: Float
  connectable: False
  default: 0.4
  description: Specify warmup proportion
outputs:
- name: Output model
  type: Model
  connectable: True
  description: The output directory where the model predictions and checkpoints will be written.
implementation:
  container:
    conda:
      content:
        name: project_environment
        channels:
        - defaults
        dependencies:
        - python=3.6.2
        - pip:
          - --extra-index-url=https://test.pypi.org/simple
          - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
          - pytorch-pretrained-bert==0.6.1
          - seqeval==0.0.5
          - tqdm==4.31.1
          - nltk==3.4
          - torchvision==0.3.0
          - pandas==0.24.1
          - pyarrow==0.12.1
          - git+https://github.com/Bowen-Guo/learn-kubeflow.git@add_ner-bert#subdirectory=ner-bert
    command:
    - python
    - train.py
    args:
    - --train_data_path
    - inputValue: Input train data
    - --bert_model
    - inputValue: BERT pretrained model
    - --max_seq_length
    - inputValue: Maximum sequence length
    - --num_train_epochs
    - inputValue: Number of training epochs
    - --warmup_proportion
    - inputValue: Warmup proportion
    - --output_model_dir
    - outputPath: Output model
